---
# From Elastcisearch example
persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0

logstashPipeline:
  uptime.conf: |
    input { exec { command => "uptime" interval => 30 } }
    output { elasticsearch { hosts => ["http://elasticsearch-master:9200"] index => "logstash" } }

# Values below were customized by alissonlima
image: "docker.elastic.co/logstash/logstash-oss"
imageTag: "7.12.0-amd64"

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "hostpath"
  resources:
    requests:
      storage: 100M
